/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCadastroTipoCarro.java
 *
 * Created on 25/08/2010, 16:04:28
 */

package boundary;

import control.ControladoraTipoCarro;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.ConexaoException;
import util.MinhaException;

/**
 *
 * @author Rodrigo Martins
 */
public class FrmCadastroTipoCarro extends javax.swing.JDialog {

    ControladoraTipoCarro cadastroTipoCarro;

    /** Creates new form FrmCadastroTipoCarro */
    public FrmCadastroTipoCarro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
        this.cadastroTipoCarro = new ControladoraTipoCarro();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNomeTipoCarro = new javax.swing.JTextField();
        jTFDescricaoTipoCarro = new javax.swing.JTextField();
        jBOK = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Tipo de Carro");
        setResizable(false);

        jLabel1.setText("Nome Tipo de Carro");

        jLabel2.setText("Descrição do Tipo de Carro");

        jBOK.setText("OK");
        jBOK.setMaximumSize(new java.awt.Dimension(80, 22));
        jBOK.setMinimumSize(new java.awt.Dimension(80, 22));
        jBOK.setPreferredSize(new java.awt.Dimension(80, 22));
        jBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKActionPerformed(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.setMaximumSize(new java.awt.Dimension(80, 22));
        jBLimpar.setMinimumSize(new java.awt.Dimension(80, 22));
        jBLimpar.setPreferredSize(new java.awt.Dimension(80, 22));
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(jTFNomeTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFDescricaoTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNomeTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFDescricaoTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKActionPerformed

        if (!this.jTFNomeTipoCarro.getText().isEmpty())
        {
            if (!this.jTFDescricaoTipoCarro.getText().isEmpty()){
                Vector novoTipoCarro = new Vector();
                novoTipoCarro.addElement(this.jTFNomeTipoCarro.getText());
                novoTipoCarro.addElement(this.jTFDescricaoTipoCarro.getText());

                try
                {
                    try {
                        try {
                            this.cadastroTipoCarro.inserirNovoTipoCarro(novoTipoCarro);
                        } catch (ConexaoException ex) {
                            Logger.getLogger(FrmCadastroTipoCarro.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        this.jTFNomeTipoCarro.setText("");
                        this.jTFDescricaoTipoCarro.setText("");
                        this.dispose();
                    } catch (MinhaException ex) {
                        Logger.getLogger(FrmCadastroTipoCarro.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                catch (SQLException erro)
                {
                    JOptionPane.showMessageDialog(null, erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }

            }else
                JOptionPane.showMessageDialog(null, "É necessário a Descrição do Tipo do Carro","Atenção" , JOptionPane.WARNING_MESSAGE);
        }else
                JOptionPane.showMessageDialog(null, "É necessário o Nome do Tipo do Carro","Atenção" , JOptionPane.WARNING_MESSAGE);


    }//GEN-LAST:event_jBOKActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        // TODO add your handling code here:
        this.jTFDescricaoTipoCarro.setText("");
        this.jTFNomeTipoCarro.setText("");
    }//GEN-LAST:event_jBLimparActionPerformed

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroTipoCarro().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFDescricaoTipoCarro;
    private javax.swing.JTextField jTFNomeTipoCarro;
    // End of variables declaration//GEN-END:variables

}
